-- BACKOFFICE.MASTER_USER_ANDI definition

CREATE TABLE "BACKOFFICE"."MASTER_USER_ANDI"
(
   "ID" NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
	"FULL_NAME" VARCHAR2(255)
);

 -- BACKOFFICE.MASTER_ACCOUNT_ANDI definition
CREATE TABLE "BACKOFFICE"."MASTER_ACCOUNT_ANDI"
(
    "ID" NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
	"BALANCE" FLOAT(53), 
	"USER_ID" NUMBER(19,0),
	constraint fk_user_id foreign key (user_id) references "BACKOFFICE"."MASTER_USER_ANDI"(ID)
);